name: QA
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - release/*
  pull_request:
    
jobs:
  main:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          VERSION=${BRANCH#release/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: What is the release version?
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.version }}
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/git_update.sh -v ${{ steps.extract_branch.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.increment-git-tag.outputs.tag}}
          release_name: "QA: Pre-Release ${{ steps.increment-git-tag.outputs.tag }}"
          draft: false
          prerelease: true